### PR TITLE
dev: Add summary information to CI runs

### PR DESCRIPTION
**Pull request by tsibley**
See commit messages for details.

See also GitHub Actions' documentation on step summaries.¹

¹ https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary

### Testing

- [x] 👀 the CI run for this PR; does it look ok?
- [x] Checks pass

### CODE REVIEW

**Comment by tsibley** [comment]
[Hey cool](https://github.com/nextstrain/conda-base/actions/runs/3644237707#summary-9956749872)

image

**Comment by tsibley** [comment]
[Check it](https://github.com/nextstrain/conda-base/actions/runs/3652022565#summary-9978478602), more summarizing and addressing #13.


Screen Shot 2022-12-08 at 14 04 31

**Comment by tsibley** [comment]
Going to merge this since it's low-risk dev-only changes and works in CI (the main point) and for me locally. I can address any review comments or issues that arise in subsequent PRs.

**Comment by corneliusroemer** [comment]
Very nice ❤️

**Pull request merged**
