### PR TITLE
Add nextclade2

### PR DESCRIPTION
**Pull request by victorlin**
## Description of proposed changes

The newest version of nextclade contains a symlink to nextclade2.¹ This will eventually replaced with a symlink to nextclade3.

To continue availability of nextclade2, add a package that provides the nextclade2 binary.²

¹ <https://github.com/bioconda/bioconda-recipes/commit/c20aa93b2f346df36d26f9c00bd059ae0c1a5dda>
² <https://github.com/bioconda/bioconda-recipes/commit/b08d5c611de349a55396ecf0735ed1f3f26e8fff>

## Related issue(s)

- https://github.com/nextstrain/private/issues/97

## Checklist

- [ ] Checks pass

### CODE REVIEW

**Comment by corneliusroemer** [comment]
I'm not sure what will happen when we have two times the same binary. Once as a symlink to Nextclade and once as a binary itself.

Will conda notice and complain? It probably should.

Nextclade==2.* and nextclade2 should be mutually exclusive, there might be a way to encode this into conda.

**Comment by victorlin** [comment]
The `nextstrain-base` package builds fine, but there is a [warning](https://github.com/nextstrain/conda-base/actions/runs/7228374575/job/19697709458?pr=48#step:8:471) when installing it and linking dependencies:

```
warning  libmamba [nextclade2-2.14.0-h9ee0642_0] The following files were already present in the environment:
    - bin/nextclade2
```

I don't see why they should be made mutually exclusive. While both of them contain `nextclade2`, those are functionally identical so it doesn't matter that one overwrites the other. Once `nextclade` no longer has `nextclade2` but instead has `nextclade3`, this allows what is currently supported in the Docker image - access to both `nextclade2` and `nextclade3`.

**Comment by corneliusroemer** [comment]
Yep this should work - though the warning is a little annoying. Up to you whether we wait or not with merging.

**Comment by corneliusroemer** [comment]
We should merge this PR soon (tomorrow) so that nextclade2 remains available when we release nextclade(3) on bioconda tomorrow

**Review by corneliusroemer — APPROVED** [review]

**Pull request merged**
